name: Remove labels

on: [issue_comment]

jobs:
  remove_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
        if: ${{ github.event.actor.login != 'fzyzcjy' }}
        with:
          labels: |
            await response
